version: '3.7'
services:
  mysql-db:
    image: mariadb
    container_name: mysql-db
    environment:
      MYSQLDB_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASES: hospital-db
      MYSQL_USER: sa
    volumes:
      #      - path_to_data:/config
      # bind mounting mysql databases
      - /c/data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - micros
  #Start PHP MY ADMIN
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpMyAdmin
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysql-db
    ports:
      - "7089:80"
    networks:
      - micros
  #Start PHP MY ADMIN
  #Start Mongo db
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - micros
  #Start consul server
  consul-server:
    image: consul:1.15
    container_name: consul-server
    ports:
      - "8500:8500"
      - "8600:8600/udp"
#    command: "agent -server -ui -node=server-1 -bsrcsrcootstrap-expect=1 -client=0.0.0.0"
    networks:
      - micros
  #End Consul server

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    environment:
      - STORAGE_TYPE=mem
      #Uncomment to enable debug logging
      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:
      - "9411:9411"
    networks:
      - micros
  #Start Spring cloud config
  config-service:
    container_name: config-service
    image: ismailharik/config-service
    ports:
      - "8888:8888"
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
    networks:
      - micros

  #Start Spring cloud config
  gateway-service:
    container_name: gateway-service
    image: ismailharik/gateway-service
    ports:
      - "9999:9999"
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
      - ZIPKIN_SERVER=zipkin-server
    networks:
      - micros

  #Start Spring cloud config
  patient-service:
    container_name: patient-service
    image: ismailharik/patient-service
    ports:
      - "8083:8083"
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
      - ZIPKIN_SERVER=zipkin-server
      - HOST_NAME=config-server
      - SPRING_CONFIG_PORT=8888
      - MONGO_PORT=27017
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - micros
  #End Patient Service
  #Start Spring cloud config
  hospital-service:
    container_name: hospital-service
    image: ismailharik/hospital-service
    ports:
      - "8085:8085"
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
      - ZIPKIN_SERVER=zipkin-server
      - HOST_NAME=config-server
      - SPRING_CONFIG_PORT=8888
      - MYSQL_HOST=mysql-db
    depends_on:
      - mysql-db
    restart: on-failure
    networks:
      - micros
  #End Patient Service
networks:
  micros:
    driver: bridge