server:
  port: 8082
spring:
  application:
    name: hospital-service
  config:
    import: optional:configserver:http://${HOST_NAME:localhost}:8888
  cloud:
    consul:
      port: ${CONSUL_PORT:8500}
      host: ${CONSUL_HOST:localhost}
    openfeign:
      client:
        default-to-properties: 'false'
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    sql:
      init:
        mode: always

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}

  logging:
    level:
      org:
        springframework:
          web:
            servlet:
              DispatcherServlet: DEBUG
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


  springdoc:
    version: '@springdoc.version@'